version: 2.1

executors:
    php73:
        working_directory: '~/project'
        docker:
          - image: 'circleci/php:7.3'

    php74:
        working_directory: '~/project'
        docker:
          - image: 'circleci/php:7.4'

commands:
    php--run-unit-tests:
        steps:
            - run:
                name: 'Run unit tests'
                command: 'phpdbg -qrr vendor/bin/phpunit'

            - store_test_results:
                path: '.phpunit/report'
            - run:
                name: 'Upload test coverage to Codacy (PHP 7.3 only)'
                command: |
                    php_version=$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;')
                    if [ "${php_version}" == "7.3" ] ; then
                        ./vendor/bin/codacycoverage clover .phpunit/clover.xml
                    fi

    php--run-static-analysis:
        steps:
            - run:
                name: 'Run syntax check'
                command: 'composer lint'
            - run:
                name: 'Run code formatting check'
                command: 'composer sniff'
            - run:
                name: 'Run static analysis'
                command: 'composer analyze'

workflows:
    version: 2

    pipeline:
        jobs:
            - fetch_code

            - php--install-dependencies:
                name: 'php73_install'
                executor_version: 'php73'
                requires: [ fetch_code ]
            - php--testing:
                name: 'php73_testing'
                executor_version: 'php73'
                requires: [ php73_install ]

            - php--install-dependencies:
                name: 'php74_install'
                executor_version: 'php74'
                requires: [ fetch_code ]
            - php--testing:
                name: 'php74_testing'
                executor_version: 'php74'
                requires: [ php74_install ]

            - fan_in:
                requires:
                    - 'php73_testing'
                    - 'php74_testing'

jobs:

    php--install-dependencies:
        parameters:
            executor_version:
                type: string

        executor: '<< parameters.executor_version >>'
        steps:
            - attach_workspace: { at: '.' }

            - restore_cache:
                keys:
                    - 'v2-<< parameters.executor_version >>-deps-{{ checksum "composer.json" }}'
                    - 'v2-<< parameters.executor_version >>-deps'

            - run:
                name: 'Install PHP dependencies'
                command: |
                    composer \
                        --no-interaction \
                        --no-progress install

                    composer show

            - save_cache:
                key: 'v2-<< parameters.executor_version >>-deps-{{ checksum "composer.json" }}'
                paths: [ 'vendor' ]

            - persist_to_workspace: { root: '.', paths: [ '.' ] }

    php--testing:
        parameters:
            executor_version:
                type: string

        executor: '<< parameters.executor_version >>'

        steps:
            - attach_workspace: { at: '.' }

            - php--run-static-analysis
            - php--run-unit-tests

    fan_in:
        executor: 'php73'
        steps: [ { run: 'whoami' } ]

    fetch_code:
        executor: 'php73'
        steps:
            - checkout
            - persist_to_workspace: { root: '.', paths: [ '.' ] }
