version: 2

php71_defaults: &php71_defaults
    working_directory: '~/project'
    docker:
        - image: 'circleci/php:7.1'

php72_defaults: &php72_defaults
    working_directory: '~/project'
    docker:
        - image: 'circleci/php:7.2'

attach_workspace: &attach_workspace
    attach_workspace:
        at: '.'

persist_workspace: &persist_workspace
    persist_to_workspace:
        root: '.'
        paths: [ '.' ]

install_libsodium: &install_libsodium
    run:
      name: 'Install PECL Libsodium (PHP 7.1 only)'
      command: |
        php_version=$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;')
        if [ "${php_version}" == "7.1" ] ; then
          sudo apt-get install libsodium-dev
          sudo pecl install libsodium
          sudo docker-php-ext-enable sodium
        fi

run_tests_steps: &run_tests_steps
    steps:
        - *attach_workspace
        - *install_libsodium
        - run:
            name: 'Run unit tests'
            command: 'phpdbg -qrr vendor/bin/phpunit'
        - store_test_results:
            path: '.phpunit/report'
        - run:
            name: 'Upload test coverage to Codacy (PHP 7.1 only)'
            command: |
                php_version=$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;')
                if [ "${php_version}" == "7.1" ] ; then
                    ./vendor/bin/codacycoverage clover .phpunit/clover.xml
                fi

workflows:

  version: 2

  pipeline:
    jobs:
      - fetch_code
      - install_php_dependencies:
          requires: [ fetch_code ]

      - linting:
          requires: [ install_php_dependencies ]
      - static_analysis:
          requires: [ install_php_dependencies ]

      - unit_tests_71:
          requires: [ linting ]

      - unit_tests_72:
          requires: [ linting ]

jobs:

    fetch_code:
        <<: *php71_defaults
        steps:
            - checkout
            - *persist_workspace

    install_php_dependencies:
        <<: *php71_defaults
        steps:
            - *attach_workspace
            - *install_libsodium

            - restore_cache:
                keys: [ 'v2-php-deps-{{ checksum "composer.json" }}', 'v2-php-deps' ]

            - run:
                name: 'Install PHP dependencies'
                command: |
                    composer --no-interaction --no-progress install
                    composer show
            - save_cache:
                key: 'v2-php-deps-{{ checksum "composer.json" }}'
                paths: [ 'vendor' ]

            - *persist_workspace

    static_analysis:
        <<: *php71_defaults
        steps:
            - *attach_workspace
            - *install_libsodium
            - run:
                name: 'Run static analysis'
                command: |
                    vendor/bin/phpstan analyse \
                    -l 4 \
                    --configuration=phpstan.neon \
                    --memory-limit=1G \
                    src
    linting:
        <<: *php71_defaults
        steps:
            - *attach_workspace

            - run:
                name: 'Run syntax check'
                command: 'vendor/bin/phplint --no-cache --ansi src'

            - run:
                name: 'Run code formatting check'
                command: |
                    vendor/bin/phpcs \
                    --colors \
                    --runtime-set ignore_warnings_on_exit true \
                    src

    unit_tests_71:
        <<: *php71_defaults
        <<: *run_tests_steps

    unit_tests_72:
        <<: *php72_defaults
        <<: *run_tests_steps
