parameters:
    global_middleware:
        - 'QL\Panthor\Middleware\EncryptedCookiesMiddleware'
        - 'QL\Panthor\Middleware\SessionMiddleware'

    cookie.settings.lifetime: '+1 year'
    session.lifetime: '+1 day'

    routes:
        hello_world:
            route: '/'
            stack: ['hello.page']
